import type { Puja, Product, Testimonial } from "./types";

const PUJA_IMG_1 = "https://images.unsplash.com/photo-1585938389612-08515b4d6b70?w=900";
const PUJA_IMG_2 = "https://images.unsplash.com/photo-1519817650390-64a93db51149?w=900";
const PUJA_IMG_3 = "https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?w=900";
const PUJA_IMG_4 = "https://images.unsplash.com/photo-1612788709349-fbca30adfa1b?w=900";
const PRODUCT_IMG_1 = "https://images.unsplash.com/photo-1606206577801-1de17d4e45b3?w=900";
const PRODUCT_IMG_2 = "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=900";
const PRODUCT_IMG_3 = "https://images.unsplash.com/photo-1605633129454-636029f4a1df?w=900";
const PRODUCT_IMG_4 = "https://images.unsplash.com/photo-1593078186734-8b1247d3f2b9?w=900";

export const MOCK_PUJAS: Puja[] = [
  {
    id: "1",
    slug: "satyanarayan-puja",
    name: "Satyanarayan Puja",
    category: "Festival",
    categorySlug: "festival",
    image: PUJA_IMG_1,
    startingPrice: 1499,
    rating: 4.9,
    reviewCount: 2847,
    duration: "2-3 hours",
    shortBenefits: [
      "Blessings of Lord Vishnu for prosperity",
      "Family peace and harmony",
      "Removes obstacles from new beginnings",
    ],
    description:
      "Satyanarayan Puja invokes Lord Vishnu for growth, peace, and wellbeing. Ideal for housewarming, birthdays, anniversaries, and business milestones.",
    whenToDo: "Full moon, Ekadashi, or any auspicious day",
    process: [
      "Sankalp and samagri setup",
      "Ganesh and Navagraha invocation",
      "Satyanarayan Katha paath",
      "Havan, aarti, and prasad distribution",
    ],
    samagriList: [
      "Panchamrit",
      "Kalash",
      "Tulsi leaves",
      "Flowers",
      "Incense",
      "Seasonal fruits",
      "Prasad ingredients",
    ],
    packages: [
      {
        id: "s1",
        name: "Basic",
        price: 1499,
        duration: "2 hrs",
        pandits: 1,
        samagri: false,
        benefits: ["1 verified pandit", "Ritual guidance", "Aarti and blessings"],
      },
      {
        id: "s2",
        name: "Gold",
        price: 2499,
        duration: "3 hrs",
        pandits: 1,
        samagri: true,
        benefits: [
          "1 verified pandit",
          "Complete samagri kit",
          "Prasad preparation",
          "Video highlights",
        ],
        popular: true,
      },
      {
        id: "s3",
        name: "Platinum",
        price: 3999,
        duration: "4 hrs",
        pandits: 2,
        samagri: true,
        benefits: [
          "2 senior pandits",
          "Premium samagri and decor",
          "Extended havan",
          "Dedicated support desk",
        ],
      },
    ],
    popular: true,
    featured: true,
  },
  {
    id: "2",
    slug: "griha-pravesh-puja",
    name: "Griha Pravesh Puja",
    category: "House Warming",
    categorySlug: "house-warming",
    image: PUJA_IMG_2,
    startingPrice: 2499,
    rating: 4.8,
    reviewCount: 1523,
    duration: "3-4 hours",
    shortBenefits: ["Purifies new home", "Brings positive energy", "Vastu balancing rituals"],
    description:
      "Traditional house-warming ceremony with vastu-focused rituals, havan, and blessings for health, harmony, and abundance.",
    whenToDo: "Best before shifting in or within first month of moving",
    process: [
      "Kalash sthapana and vastu sankalp",
      "Ganesh pujan and navagraha shanti",
      "Havan and griha shuddhi",
      "Aarti and prasad",
    ],
    samagriList: ["Coconut", "Mango leaves", "Havan samagri", "Ghee", "Flowers"],
    packages: [
      {
        id: "g1",
        name: "Basic",
        price: 2499,
        duration: "3 hrs",
        pandits: 1,
        samagri: false,
        benefits: ["1 pandit", "Vastu rituals", "Aarti"],
      },
      {
        id: "g2",
        name: "Gold",
        price: 3499,
        duration: "4 hrs",
        pandits: 1,
        samagri: true,
        benefits: ["Complete samagri", "Havan setup", "Prasad"],
        popular: true,
      },
      {
        id: "g3",
        name: "Platinum",
        price: 5499,
        duration: "5 hrs",
        pandits: 2,
        samagri: true,
        benefits: ["2 pandits", "Premium setup", "Personal coordinator"],
      },
    ],
    popular: true,
    featured: true,
  },
  {
    id: "3",
    slug: "mahamrityunjaya-jaap",
    name: "Mahamrityunjaya Jaap",
    category: "Health & Peace",
    categorySlug: "health",
    image: PUJA_IMG_3,
    startingPrice: 2199,
    rating: 4.9,
    reviewCount: 931,
    duration: "2-3 hours",
    shortBenefits: ["Health and strength", "Removes negativity", "Mental peace"],
    description:
      "A sacred jaap dedicated to Lord Shiva for healing, positivity, and inner peace.",
    whenToDo: "During health concerns, birthdays, or monthly pradosh",
    process: ["Sankalp", "108 mantra jaap", "Havan", "Aarti"],
    samagriList: ["Bilva leaves", "Rudraksha", "Gangajal", "Ghee", "Flowers"],
    packages: [
      {
        id: "m1",
        name: "Basic",
        price: 2199,
        duration: "2 hrs",
        pandits: 1,
        samagri: false,
        benefits: ["108 chants", "Aarti", "Blessing note"],
      },
      {
        id: "m2",
        name: "Gold",
        price: 3199,
        duration: "3 hrs",
        pandits: 1,
        samagri: true,
        benefits: ["Complete samagri", "Havan", "Prasad"],
        popular: true,
      },
      {
        id: "m3",
        name: "Platinum",
        price: 4999,
        duration: "4 hrs",
        pandits: 2,
        samagri: true,
        benefits: ["2 pandits", "Extended jaap", "Video call attendance"],
      },
    ],
    featured: true,
  },
  {
    id: "4",
    slug: "mundan-ceremony",
    name: "Mundan Ceremony",
    category: "Sanskar",
    categorySlug: "sanskar",
    image: PUJA_IMG_4,
    startingPrice: 999,
    rating: 4.7,
    reviewCount: 892,
    duration: "2 hours",
    shortBenefits: ["Sacred head tonsure", "Blessings for child"],
    description: "Traditional Mundan ceremony for your child's first haircut.",
    featured: true,
  },
  {
    id: "5",
    slug: "rudrabhishek-puja",
    name: "Rudrabhishek Puja",
    category: "Festival",
    categorySlug: "festival",
    image: PUJA_IMG_3,
    startingPrice: 1799,
    rating: 4.8,
    reviewCount: 1102,
    duration: "2-3 hours",
    shortBenefits: ["Shiva blessings", "Career growth", "Family protection"],
    description: "Powerful abhishek ritual for Lord Shiva done with Vedic mantras.",
    featured: true,
    popular: true,
  },
  {
    id: "6",
    slug: "lakshmi-kuber-puja",
    name: "Lakshmi Kuber Puja",
    category: "Prosperity",
    categorySlug: "prosperity",
    image: PUJA_IMG_1,
    startingPrice: 1999,
    rating: 4.8,
    reviewCount: 774,
    duration: "2-3 hours",
    shortBenefits: ["Financial blessings", "Business growth", "Prosperity rituals"],
    description: "Dedicated puja for Goddess Lakshmi and Lord Kuber for abundance.",
    featured: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "rudraksha-mala",
    name: "Premium Rudraksha Mala (108 beads)",
    category: "rudraksha",
    images: [PRODUCT_IMG_1, PRODUCT_IMG_3, PRODUCT_IMG_4],
    price: 1499,
    originalPrice: 1999,
    discount: 25,
    rating: 4.8,
    reviewCount: 342,
    benefits: ["Natural stress relief", "Spiritual vibration", "Authentic Nepal origin"],
    description: "Hand-strung 108 bead Rudraksha mala from Nepal.",
    inStock: true,
    isAuthentic: true,
    featured: true,
  },
  {
    id: "2",
    slug: "hanuman-chalisa-book",
    name: "Hanuman Chalisa (Hardcover)",
    category: "books",
    images: [PRODUCT_IMG_2, PRODUCT_IMG_4],
    price: 199,
    originalPrice: 299,
    discount: 33,
    rating: 4.9,
    reviewCount: 1256,
    benefits: ["Blessed text", "Easy to read", "Durable"],
    description: "High quality printed Hanuman Chalisa for daily reading.",
    inStock: true,
    featured: true,
  },
  {
    id: "3",
    slug: "havan-samagri-kit",
    name: "Complete Havan Samagri Kit",
    category: "samagri",
    images: [PRODUCT_IMG_4, PRODUCT_IMG_1],
    price: 899,
    originalPrice: 1199,
    discount: 25,
    rating: 4.7,
    reviewCount: 468,
    benefits: ["Curated by pandits", "Pure ingredients", "Ready-to-use packs"],
    description: "All-in-one puja and havan samagri kit for home rituals.",
    inStock: true,
    isAuthentic: true,
    featured: true,
  },
  {
    id: "4",
    slug: "brass-lakshmi-idol",
    name: "Brass Lakshmi Idol",
    category: "idols",
    images: [PRODUCT_IMG_3, PRODUCT_IMG_2],
    price: 1299,
    rating: 4.6,
    reviewCount: 208,
    benefits: ["Premium brass finish", "Temple-grade detailing", "Ideal for daily puja"],
    description: "Finely crafted brass Lakshmi idol for home mandir.",
    inStock: true,
    isAuthentic: true,
    featured: true,
  },
  {
    id: "5",
    slug: "chandan-incense-pack",
    name: "Chandan Incense Pack",
    category: "incense",
    images: [PRODUCT_IMG_2, PRODUCT_IMG_1],
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.7,
    reviewCount: 598,
    benefits: ["Long burning", "Natural fragrance", "Daily puja essential"],
    description: "Premium sandalwood incense sticks crafted for sacred ambiance.",
    inStock: true,
    featured: true,
  },
  {
    id: "6",
    slug: "silver-plated-puja-thali",
    name: "Silver Plated Puja Thali Set",
    category: "jewelry",
    images: [PRODUCT_IMG_4, PRODUCT_IMG_3],
    price: 2199,
    rating: 4.8,
    reviewCount: 156,
    benefits: ["Elegant gifting", "Durable build", "Includes diya and katori set"],
    description: "Premium silver-plated thali designed for festive rituals.",
    inStock: true,
    isAuthentic: true,
    featured: true,
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Priya S.",
    location: "Mumbai",
    rating: 5,
    text: "Panditji arrived on time and completed Satyanarayan Puja beautifully. Whole flow felt premium and stress-free.",
  },
  {
    id: "2",
    name: "Rahul K.",
    location: "Delhi",
    rating: 5,
    text: "Career astrology consultation was practical and clear. Booking and call process was super smooth.",
  },
  {
    id: "3",
    name: "Anita M.",
    location: "Bangalore",
    rating: 4,
    text: "Griha Pravesh package included every samagri item and support stayed connected till puja completion.",
  },
  {
    id: "4",
    name: "Manoj P.",
    location: "Pune",
    rating: 5,
    text: "Temple VIP darshan booking saved hours of queue time. Team handled coordination end to end.",
  },
];
